apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitbucket-deployment
  namespace: production
  labels:
    service: bitbucket
    app: bitbucket

spec:
  replicas: 1
  selector:
    matchLabels:
      app: bitbucket
  template:
    metadata:
      labels:
        app: bitbucket
    spec:
      containers:
        - name: bitbucket
          image: atlassian/bitbucket-server:latest
          imagePullPolicy: Always
          env:
            - name: JVM_MINIMUM_MEMORY
              value: 1024m
            - name: JVM_MAXIMUM_MEMORY
              value: 1024m
          ports:
            - containerPort: 7990
          volumeMounts:
          - mountPath: "/var/atlassian/application-data/bitbucket"
            name: nfs
      volumes:
      - name: nfs
        persistentVolumeClaim:
          claimName: nfsprodbitbucket
