apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{bamboovolumename}}
  namespace: {{namespace}}
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: {{storagesize}}