apiVersion: v1
kind: Service
metadata:
  name: bitbucket
  namespace: production
  labels:
    app: bitbucket
spec:
  type: LoadBalancer
  externalIPs:
    - 10.1.1.24
    - 10.1.1.25
  ports:
  - name: http
    port: 7990
    targetPort: 7990
    protocol: TCP
  selector:
    app: bitbucket