apiVersion: v1
kind: Service
metadata:
  name: fecru
  namespace: production
  labels:
    app: fecru
spec:
  type: LoadBalancer
  externalIPs:
    - 10.1.1.24
    - 10.1.1.25
  ports:
  - name: http
    port: 8060
    targetPort: 8060
    protocol: TCP
  selector:
    app: fecru