apiVersion: v1
kind: Service
metadata:
  name: {{bambook8sservicename}}
  namespace: {{namespace}}
  labels:
    app: {{appname}}
spec:
  type:
  externalIPs:
   - {{ nodeip1 }}
   - {{ nodeip2 }}
  ports:
  - name: http
    port: 8085
    targetPort: 8085
    protocol: TCP
  selector:
    app: {{appname}}