apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: production
  name: nfsprodbamboo
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteMany
  nfs:
    server: 172.22.48.39
    path: "/nfsdata/prod_bamboo"