apiVersion: v1
kind: Service
metadata:
  name: bamboo
  namespace: production
  labels:
    app: bamboo
spec:
  type: LoadBalancer
  externalIPs:
    - 10.1.1.24
    - 10.1.1.25
  ports:
  - name: http
    port: 8085
    targetPort: 8085
    protocol: TCP
  selector:
    app: bamboo