apiVersion: apps/v1
kind: Deployment
metadata:
  name: bamboodeployment
  namespace: {{namespace}}
  labels:
    service: {{bambooservicename}}
    app: {{appname}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{appname}}
  template:
    metadata:
      labels:
        app: {{appname}}
    spec:
      containers:
        - name: bamboo
          image: dchevell/bamboo:latest
          imagePullPolicy: Always
          env:
            - name: JVM_MINIMUM_MEMORY
              value: {{jvmlow}}
            - name: JVM_MAXIMUM_MEMORY
              value: {{jvmhigh}}
          ports:
            - containerPort: 8085
          volumeMounts:
          - mountPath: "/var/atlassian/application-data/bamboo"
            name: {{bamboovolume}}
      volumes:
      - name: {{bamboovolume}}
        persistentVolumeClaim:
          claimName: {{bamboovolumeclaim}}
