apiVersion: v1
kind: Service
metadata:
  name: jira
  namespace: {{namespace}}
  labels:
    app: jira
spec:
  type: LoadBalancer
  externalIPs:
    - {{nodeip1}}
    - {{nodeip2}}
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: jira