apiVersion: apps/v1
kind: Deployment
metadata:
  name: jira-deployment
  namespace: {{ namespace }}
  labels:
    service: jira
    app: jira

spec:
  replicas: 1
  selector:
    matchLabels:
      app: jira
  template:
    metadata:
      labels:
        app: jira
    spec:
      containers:
        - name: jira
          image: dchevell/jira-software:latest
          imagePullPolicy: Always
          env:
            - name: JVM_MINIMUM_MEMORY
              value: {{xms}}
              # 1536m
            - name: JVM_MAXIMUM_MEMORY
              value: {{xmx}}
              # 1536m
            - name: CATALINA_CONNECTOR_PROXYNAME
              value: {{proxyname}}
              # jira.company.com
            - name: CATALINA_CONNECTOR_SCHEME
              value: {{httpscheme}}
              # https
            - name: CATALINA_CONNECTOR_SECURE
              value: {{secureconnector}}
              # Value = "true
          ports:
            - containerPort: 8080
          volumeMounts:
          - mountPath: "/var/atlassian/application-data/jira"
            name: {{ volume }}
      volumes:
      - name: {{ volume }}
        persistentVolumeClaim:
          claimName: {{ volumeclaim }}
