apiVersion: apps/v1
kind: Deployment
metadata:
  name: jira-deployment
  namespace: {{namespace}}
  labels:
    service: {{jiraservicename}}
    app: {{appname}}

spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{appname}}
  template:
    metadata:
      labels:
        app: {{appname}}
    spec:
      containers:
        - name: jira
          image: dchevell/jira-software:latest
          imagePullPolicy: Always
          env:
            - name: JVM_MINIMUM_MEMORY
              value: {{jvmlow}}
              # 1536m
            - name: JVM_MAXIMUM_MEMORY
              value: {{jvmhigh}}
              # 1536m
            - name: CATALINA_CONNECTOR_PROXYNAME
              value: {{proxyname}}
              # jira.company.com
            - name: CATALINA_CONNECTOR_SCHEME
              value: {{proxyscheme}}
              # https
            - name: CATALINA_CONNECTOR_SECURE
              value: {{proxysecure}}
              # Value = "true
          ports:
            - containerPort: 8080
          volumeMounts:
          - mountPath: "/var/atlassian/application-data/jira"
            name: {{jiravolume}}
      volumes:
      - name: {{jiravolume}}
        persistentVolumeClaim:
          claimName: {{ jiravolumeclaim }}
