apiVersion: apps/v1
kind: Deployment
metadata:
  name: jira-deployment
  namespace: production
  labels:
    service: jira
    app: jira

spec:
  replicas: 1
  selector:
    matchLabels:
      app: jira
  template:
    metadata:
      labels:
        app: jira
    spec:
      containers:
        - name: jira
          image: dchevell/jira-software:latest
          imagePullPolicy: Always
          env:
            - name: JVM_MINIMUM_MEMORY
              value: 1536m
            - name: JVM_MAXIMUM_MEMORY
              value: 1536m
            - name: CATALINA_CONNECTOR_PROXYNAME
              value: jira.pandanet.xyz
            - name: CATALINA_CONNECTOR_SCHEME
              value: https
            - name: CATALINA_CONNECTOR_SECURE
              value: "true"
          ports:
            - containerPort: 8080
          volumeMounts:
          - mountPath: "/var/atlassian/application-data/jira"
            name: nfs
      volumes:
      - name: nfs
        persistentVolumeClaim:
          claimName: nfsprodjira
