apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfsprodjira
  namespace: production
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi