apiVersion: v1
kind: Service
metadata:
  name: jira
  namespace: production
  labels:
    app: jira
spec:
  type: LoadBalancer
  externalIPs:
    - 10.1.1.24
    - 10.1.1.25
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: jira